begin branch versioning for docs-node
mongodb/docs-worker-pool pull request #383
Opened 2021-03-03 20:21 UTC by terakilobyte

It's finally happened, there's a new version of the node driver coming out.

2021-03-04 17:05 UTC, sophstad requested changes

2021-03-04 17:05 UTC, sophstad commented on publishedbranches/docs-node.yaml
> +    manual: 'v4.0'
This field should correspond to the branch name, which I presume to be `master` from line 15!
```suggestion
    manual: 'master'
```

2021-03-04 18:30 UTC, sophstad approved these changes

2021-03-04 18:31 UTC, sophstad commented
@terakilobyte When are the v4 docs set to be published? I want to make sure we schedule the alias branch work appropriately!

2021-03-04 19:07 UTC, terakilobyte commented
@sophstad Right now we think they'll go GA by the 20th of March, though that could slip. If it'd help we can cut a placeholder v4.0 branch now?

2021-03-11 20:47 UTC, schmalliso approved these changes

2021-03-11 20:47 UTC, merged