DOP-4242: Use release, not tag push for CI/CD
mongodb/docs-worker-pool pull request #968
Opened 2024-01-19 17:30 UTC by mayaraman19

[DOP-4242](https://jira.mongodb.org/browse/DOP-4242)

This PR changes all instances of `on.push.tag` to `on.release` so that the CI/CD workflow is only activated upon release. please ignore the commit history :sob:

2024-01-22 21:01 UTC, seungpark requested changes
This will be a good opportunity to update the readme for releases! 🙏

2024-01-22 21:32 UTC, mayaraman19 commented on .github/workflows/deploy-prd-ecs.yml
> +    types: [released]
I talked about this with Cassidy and he told me to use `released`, but I'll confirm with him!

2024-01-23 16:27 UTC, casthewiz commented on .github/workflows/deploy-prd-ecs.yml
> +    types: [released]
@seungpark We don't want to catch drafts as a part of this action - I want our releases to be highly intentional and as tightly scoped as possible 👍

2024-01-23 17:10 UTC, seungpark commented on .github/workflows/deploy-prd-ecs.yml
> +    types: [released]
@casthewiz not creation of a draft, but transitioning a draft to published will not be caught within `released` types as in the first link above.

if this is still desirable, @mayaraman19 we should add to the [base readme of steps to release](https://github.com/mongodb/docs-worker-pool/blob/master/README.md#release-process). will pushing a tag fire a release? - i'm not sure of this. or do we need to use `gh release`

2024-01-23 17:17 UTC, mayaraman19 commented on .github/workflows/deploy-prd-ecs.yml
> +    types: [released]
@seungpark based on testing with my dummy repository linked in the comment, I think that transitioning from draft to published should actually trigger the CI/CD workflow. 

And yes, I should update the base readme. Pushing a tag should not fire a release.

2024-01-23 17:34 UTC, seungpark commented on .github/workflows/deploy-prd-ecs.yml
> +    types: [released]
!! thanks for the test repo. forked and tested! https://github.com/seungpark/actions-test/actions. LGTM. i have seen some SO posts about the ambiguity of `released` vs `published` in the docs....

tested with GH UI that draft -> published does in fact fire this

2024-01-24 14:50 UTC, seungpark approved these changes
LGTM. minor notes below!

2024-01-24 14:50 UTC, seungpark commented on README.md
> +- Create a release associated with the tag using the GitHub UI or by running `gh release create`.
might be an extra space at end of line, based [on error](https://github.com/mongodb/docs-worker-pool/actions/runs/7631054222/job/20788127472?pr=968)

2024-01-24 14:50 UTC, seungpark commented on .github/workflows/README.md
> +The release process occurs whenever someone releases a specific tag via the GitHub UI. Three separate workflows are run upon release:
minor nitpick. not specific to the Github UI

2024-01-24 15:08 UTC, merged